eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8758
spring:
  application:
    name: service-member
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

#添加扫包
swagger:
  base-package: com.example.memberservice.controller