eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8764
spring:
  application:
    name: service-order
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1
feign:
  hystrix:
    enabled: true
#hystrix:
#  command:
      #     default:
      #       execution:
      #         isolation:
      #           thread:
      #            timeoutInMilliseconds: 2000
mybatis:
  mapper-locations: classpath:mapper/*.xml


#添加扫包
swagger:
  base-package: com.example.ordersservice.controller

